services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: barapp
      POSTGRES_USER: barapp
      POSTGTRES_DB: barapp
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:  
  postgres-data:
  
